services:
  redis:
    container_name: redis-Mailtracker
    image: redis
    restart: always
    ports:
      - 9379:6379
  mongo:
    container_name: mongo-Mailtracker
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
  mongo-express:
    container_name: mongo-express-Mailtracker
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
